### ISSUE TITLE
Clone Failed

### ISSUE THREAD

**Issue by BeauCranston** [dumbmatter/zengm-legacy#1]
I am able to clone the repo, however I am unable to checkout the working tree. There is also a problem with one of the font paths. 

error: invalid path 'moba/electron/src/mirror/fonts.googleapis.com/css?family=Lato:400,400italic,700'

**Comment by dumbmatter** [comment]
Not sure what that means, sorry. It's a git repo with a single branch, I'm not sure what it means to be able to clone it but still not have it work. Maybe it's a problem with git on your computer?

Feel free to send a PR to fix broken URLs.

**Comment by BeauCranston** [comment]
Haha, I wish I knew too. I've always been able to fork a repo and then just clone it but this repo didn't work. Basically I got the files but git would not make the link to the remote repo and I think it's directly related to the font error. I'll investigate and see if fixing the font error also fixes my inability to clone.

**Comment by BeauCranston** [comment]
Created a pull request with the font deleted since it allowed me to clone properly. Also I'm a huge fan lol. Played Basketball gm for about 500+ hours and I love the work you did, you should be really proud. I also really like LOL GM but it was too slow so the reason why I am cloning is to see if I can do bug fixes on it, and possibly make it faster. Thanks!

**Comment by dumbmatter** [comment]
Thanks! All the projects in this repo are very old and not in the best condition, so I wish you luck, but it'll probably be an uphill battle...

**Comment by BeauCranston** [comment]
Yeah there's only about 8000 files to look through :). Oh well this is my first time trying to contribute to a project that's not my own so I'm gonna have a blast with this. Thanks for making this available to the community, you are a real one!
